// <auto-generated />
using System;
using BagShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BagShop.Migrations
{
    [DbContext(typeof(BagContext))]
    [Migration("20260616135017_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BagStore.Models.Bag", b =>
                {
                    b.Property<int>("BagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BagId"), 1L, 1);

                    b.Property<string>("BagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BagId");

                    b.HasIndex("UserId");

                    b.ToTable("Bags");

                    b.HasData(
                        new
                        {
                            BagId = 1,
                            BagName = "Classic Leather Bag",
                            Brand = "Zara",
                            Color = "Black",
                            Price = 45.99m,
                            UserId = 1
                        },
                        new
                        {
                            BagId = 2,
                            BagName = "Mini Crossbody Bag",
                            Brand = "Mango",
                            Color = "Beige",
                            Price = 29.99m,
                            UserId = 1
                        },
                        new
                        {
                            BagId = 3,
                            BagName = "Travel Backpack",
                            Brand = "Nike",
                            Color = "Gray",
                            Price = 65.00m,
                            UserId = 2
                        },
                        new
                        {
                            BagId = 4,
                            BagName = "Elegant Handbag",
                            Brand = "Guess",
                            Color = "Brown",
                            Price = 75.50m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BagStore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "sara@gmail.com",
                            FullName = "Sara Ahmad",
                            Password = "123"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "rawan@gmail.com",
                            FullName = "Rawan Ali",
                            Password = "456"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "noor@gmail.com",
                            FullName = "Noor Omar",
                            Password = "789"
                        });
                });

            modelBuilder.Entity("BagStore.Models.Bag", b =>
                {
                    b.HasOne("BagStore.Models.User", "User")
                        .WithMany("Bags")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BagStore.Models.User", b =>
                {
                    b.Navigation("Bags");
                });
#pragma warning restore 612, 618
        }
    }
}
